#!/bin/sh
#PBS -N hno5Z
#PBS -S /bin/bash
#PBS -j oe
#PBS -W umask=022
#PBS -l ncpus=4
#PBS -l mem=32gb
#PBS -l walltime=96:00:00

module load intel
module load mvapich2
module load pbspro
export PATH=/usr/local/apps/molpro/2015.1.35/bin:$PATH

export WORKDIR=$PBS_O_WORKDIR
export TMPDIR=/tmp/$USER/$PBS_JOBID
cd $WORKDIR
mkdir -p $TMPDIR

date
hostname
molpro -t 4 opt.com
qstat -f $PBS_JOBID
date

rm -rf $TMPDIR

